import Link from "next/link";
import React from "react";

const TermsPage = () => {
  return (
    <div className="p-4 sm:px-8 xl:px-20 space-y-6 max-w-2xl mx-auto mb-10">
      <div className="space-y-3">
        <h1 className="text-3xl font-bold">Terms & Conditions</h1>
        <h2 className="text-lg sub-heading ">Effective Date: 06/10/2024</h2>
      </div>
      <p className="text-balance">
        Welcome to{" "}
        <Link
          href={"/"}
          className="text-white hover:text-blue-500 underline underline-offset-1 transition-colors duration-300 font-italic"
        >
          Code image
        </Link>{" "}
        . By accessing or using this website, you agree to comply with these
        Terms & Conditions. If you do not agree with any part of these terms,
        please do not use our website.
      </p>
      <div className="sub">
        <h3 className="sub-heading">Age Limit</h3>
        <p className="text-balance">
          There are no age restrictions for using this website. By using this
          website, you affirm that you have the legal capacity to enter into
          these Terms & Conditions.
        </p>
      </div>
      <div className="sub">
        <h3 className="sub-heading">Data Privacy</h3>
        <p className="text-balance">
          We do not collect, store, or process any personal information from
          users. No data is saved, tracked, or recorded in any form.
        </p>
      </div>
      <div className="sub">
        <h3 className="sub-heading">Copyright and Ownership</h3>
        <p className="text-balance space-y-3">
          All images and content generated by users through the tools and
          services available on this website (&quot;User-Generated
          Content&quot;) are owned by the users. Users have full rights to use,
          modify, share, or distribute their generated content without any
          restrictions or obligations to{" "}
          <span className="name-w "> Code Image</span> .
        </p>
        <p className="text-balance">
          <span className="name-w "> Code Image</span> does not claim any
          ownership over User-Generated Content and allows users to use it
          royalty-free for any purpose.
        </p>
        <p className="text-balance">
          All designs, code, and content on{" "}
          <span className="name-w "> Code Image</span> are protected by
          copyright laws. The copyright is owned by the developer{" "}
          <Link
            href={"https://www.ankurghosh.xyz"}
            className="text-white hover:text-blue-500 underline underline-offset-1 transition-colors duration-300 font-italic"
          >
            Ankur Ghosh
          </Link>
          .
        </p>
      </div>
      <div className="sub">
        <h3 className="sub-heading">Limitation of Liability</h3>
        <p className="text-balance">
          Wesite or the developer of this website not be liable for any direct,
          indirect, incidental, or consequential damages arising from your use
          of{" "}
          <Link href={"/"} className="name-w-hover">
            Code Image
          </Link>
          . We make no warranties regarding the reliability or accuracy of our
          services.
        </p>
      </div>
      <div className="sub">
        <h3 className="sub-heading">Modifications to Terms</h3>
        <p className="text-balance">
          We reserve the right to modify these Terms and Conditions at any time.
          Any changes will be effective immediately upon posting. Your continued
          use of{" "}
          <Link href={"/"} className="name-w-hover">
            Code Image
          </Link>{" "}
          after changes indicates your acceptance of the new Terms and
          Conditions.
        </p>
      </div>
      <div className="sub">
        <h3 className="sub-heading">Contact Information</h3>
        <p className="text-balance">
          For any questions about these Terms and Conditions, please contact us
          at:{" "}
          <Link
            href={"mailto:ankur@ankurghosh.xyz"}
            className="text-white hover:text-blue-500 underline underline-offset-1 transition-colors duration-300 font-italic"
          >
            ankur@ankurghosh.xyz
          </Link>{" "}
          .
        </p>
      </div>
    </div>
  );
};

export default TermsPage;
